[www]
; Usuário e grupo que o processo vai usar
user = www-data
group = www-data

; Onde o PHP-FPM vai "escutar" por conexões.
; Este caminho DEVE ser o mesmo usado no nginx.conf.
listen = /var/www/html/run/php-fpm.sock

; Garante que o Nginx tenha permissão para ler/escrever no socket
listen.owner = www-data
listen.group = www-data
listen.mode = 0660

; Configurações de gerenciamento de processos
pm = dynamic
pm.max_children = 5
pm.start_servers = 2
pm.min_spare_servers = 1
pm.max_spare_servers = 3